server:
  port: 9004

spring:  application:    name: PAYMENT-SERVICE
      h2:    console:      enabled: true
        datasource:    url: jdbc:h2:mem:testdb
  jpa:    show-sql: true
    
    
eureka:  client:    fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: http://localhost:8761/eureka/

