server:
  port: 9002

spring:  application:    name: PAYMENT-SERVICE
      h2:    console:      enabled: true
        datasource:    url: jdbc:h2:mem:testdb
  jpa:    show-sql: true
    
   
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://65.0.133.155:8761/eureka
  instance:
    hostname: 65.0.133.155:8761


