product:
  price: 56000.525

server:
  port: 9001
 
  
spring:  application:    name: ORDER-SERVICE
    
  jpa:    show-sql: true
      h2:    console:      enabled: true
        datasource:    url: jdbc:h2:mem:testdb
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://65.0.133.155:8761/eureka
  instance:
    hostname: 65.0.133.155:8761
