server:
  port: 9003

spring:  application:    name: ACCOUNTS-SERVICE
      h2:    console:      enabled: true
        datasource:    url: jdbc:h2:mem:testdb
  jpa:    show-sql: true
    
  config:
    import: optional:configserver:http://localhost:9555
    
    


