server:
  port: 9003

spring:  application:    name: ACCOUNTS-SERVICE
      h2:    console:      enabled: true
        datasource:    url: jdbc:h2:mem:testdb
  jpa:    show-sql: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://13.234.113.166:8761/eureka
  instance:
    hostname: 13.234.113.166:8761
    
    


